theme: jekyll-theme-slate
title: Trong Pattle
description: I am a final-year student in the major of Space Science and Satellite Technology (SSST), Deparment of Space and Applications (SA) at University of Science and Technology of Hanoi (USTH). 
